#!/bin/bash
set -e #fail on error

mkdir -p ./build/tmp

rm ./build/tmp/application.zip || true
rm ./build/delta.chat.zip || true

cp ./metadata.json ./build/tmp/metadata.json

cd dist

zip -qr ../build/tmp/application.zip .

cd ../build/tmp

zip -qr ../delta.chat.zip .

echo "Created delta.chat.zip"